쿼리 유사도 반영 검색 결과 적용하기
teacher-coder/picture-muvie pull request #101
Opened 2023-03-05 06:37 UTC by Ridealist

1. 쿼리 - 곡 정보 문자열 유사도 적용
- thefuzz 라이브러리 설치 https://github.com/seatgeek/thefuzz
- query <-> title 간의 partial_token_sort_ratio 적용
- 위 score가 offset 보다 크면 바로 return
- offset보다 작으면 최대값을 갱신하며 looping 돌기

2. 곡 정보, 가수 정보 띄어쓰기 살려서 텍스트 받아오도록 수정
- 띄어쓰기 기준 토근화 -> 단어 유사도 계산 방식이므로 띄어쓰기 살리도록 코드 수정

2023-03-08 14:43 UTC, hoetaek requested changes
형 수고했어!!
몇가지만 좀 바꿔봤는데, 파이썬에서는 최대값을 구할 때 max 함수를 사용하는 게 좀 편하더라고
그리고 조건들이 모두 흩어져 있으면 가독성이 떨어지니까 조건 모아두는 것만 해뒀어~

2023-03-08 14:43 UTC, hoetaek commented on backend/picture_muvie/utils/naver_search.py
> +                max_similarity_score = cur_score
```suggestion
            max_similarity_score = max(cur_score, max_similarity_score)
```

2023-03-08 14:43 UTC, hoetaek commented on backend/picture_muvie/utils/naver_search.py
> +            cur_score = fuzz.partial_token_sort_ratio(query, temp_title + " " + temp_artist)
```suggestion
            source = host_dict[host]["source"]
            title = search_data["title"]
            artist =  search_data["artist"]
            lyrics = search_data["lyrics"]
            cur_score = fuzz.partial_token_sort_ratio(query, title + " " + artist)
```

2023-03-08 14:44 UTC, hoetaek commented
@Ridealist fuzz 재밌는 라이브러리네!ㅋㅋㅋㅋ 덕분에 새로운 라이브러리 공부했습니다~

2023-03-09 11:53 UTC, Ridealist commented on backend/picture_muvie/utils/naver_search.py
> +                continue
오키 if 문을 아예 합쳐버려도 괜찮겠다!

2023-03-09 11:53 UTC, Ridealist commented on backend/picture_muvie/utils/naver_search.py
> +            cur_score = fuzz.partial_token_sort_ratio(query, temp_title + " " + temp_artist)
이건 내가 temp라는 별도 변수를 만든 이유가 있는데,
내 생각에 similarity가 너무 낮으면 아예 가사가 없다고 나오는게 더 사용성이 낫다고 생각했거든.
(이상한 가사가 나올 바에는 복붙하도록 하는거지)
그래서 일단 temp 변수에 저장해 놓고, similarity_score를 비교한 다음 그게 일정 수준 이상이면 원래 변수에 할당한다
이런 로직으로 생각해서 짰었어~

2023-03-09 11:53 UTC, Ridealist commented on backend/picture_muvie/utils/naver_search.py
> +            cur_score = fuzz.partial_token_sort_ratio(query, temp_title + " " + temp_artist)
회택이 너가 제안한 구조처럼 매번 원래 변수에 할당해버리면
similarity score가 낮은 상태에서 끝까지 looping을 돌고서(break 되지 않은채로)
가장 마지막 가사가 변수에 할당되어 있어서, 의미없는 가사가 화면에 나오게 될 수 있어.
@hoetaek

2023-03-09 13:07 UTC, hoetaek commented on backend/picture_muvie/utils/naver_search.py
> +            cur_score = fuzz.partial_token_sort_ratio(query, temp_title + " " + temp_artist)
그럼 여기서 lyrics 변수 할당만 하지말고 아래에서 하면 될듯! @Ridealist 

            if max_similarity_score > SIMILARITY_SCORE_OFFSET:
                lyrics = search_data["lyrics"]
                break

2023-03-09 13:10 UTC, hoetaek commented on backend/picture_muvie/utils/naver_search.py
> +                continue
이거 내가 잘못 생각해서 좀 수정해야 함!ㅋㅋㅋ
lyrics key가 있는지 없는지 보는데 아니라 lyrics key에 다한 value가 None이 아닌지를 봐야할듯 @Ridealist

2023-03-09 13:34 UTC, hoetaek requested changes
lyrics 변수에 할당하는 걸 max offset 넘었을 때 하는 방향으로 ㄱㄱ

2023-03-09 15:00 UTC, Ridealist commented on backend/picture_muvie/utils/naver_search.py
> +            cur_score = fuzz.partial_token_sort_ratio(query, temp_title + " " + temp_artist)
그럼 source, title, artist 변수에는 값이 할당되고 lyrics에는 값이 None인 경우가 생길거거든?
프론트엔드에서  가사를 못찾았다고 하는 메세지는 오로지 lyrics 필드 값만 영향 받는 건가? @hoetaek

2023-03-09 15:01 UTC, Ridealist commented on backend/picture_muvie/utils/naver_search.py
> +            if not search_data or ("lyrics" not in search_data) or (len(search_data["lyrics"]) <= MINIMUM_LYRICS_LENGTH):
엉 맞어 나도 생각해보니 그렇더라ㅋㅋㅋㅋㅋ
수정해서 push 했어~

2023-03-09 15:02 UTC, hoetaek commented on backend/picture_muvie/utils/naver_search.py
> +            cur_score = fuzz.partial_token_sort_ratio(query, temp_title + " " + temp_artist)
응응 api.py 파일에서 확인했음! @Ridealist

2023-03-09 15:04 UTC, hoetaek commented on backend/picture_muvie/utils/naver_search.py
> +            cur_score = fuzz.partial_token_sort_ratio(query, temp_title + " " + temp_artist)
가독성에 있어서 temp 변수는 피할 수 있을 때 피하는 게 좋을듯
source나 lyrics 같은 경우에는 마지막에 정의할 때 외에는 이 함수 안에서 재사용되지 않으니까 굳이 중간 부분에서 정의 안 내려줘도 될 것 같아

2023-03-09 15:21 UTC, Ridealist commented on backend/picture_muvie/utils/naver_search.py
> +            cur_score = fuzz.partial_token_sort_ratio(query, temp_title + " " + temp_artist)
맞어 temp 변수가 들어가니 가독성이 많이 떨어지더라고...
또 필요 없는 변수 생성이 자원 소모이기도 하니 좋은 피드백이었다~
반영해서 push 했으:)
0)

2023-03-09 15:21 UTC, merged