Docker Settings for local server
teacher-coder/picture-muvie pull request #15
Opened 2023-02-08 18:40 UTC by Ridealist

- 실행 방법
1. `docker-compose up --build` 로 image 및 container 생성
2. http://localhost:8000 요청이 **nginx container** 에서 잘 처리되는지 확인

- 주요 변화
1. backend 디렉토리 생성 및 장고 및 파이썬 관련 파일들 모두 통합 관리
2. postgresql DB 적용
3. nginx 적용
4. backend / frontend / nginx / postgresql 모두 개별 docker image 생성 및 컨테이너화

2023-02-09 05:53 UTC, Ridealist commented
참고한 reference

main
- https://gitlab.com/briancaffey/docker-nginx-django-vue-architecture/-/tree/master/

sub
- https://github.com/ju-c/docker-django-drf-vue-nginx
- https://learndjango.com/tutorials/django-docker-and-postgresql-tutorial
- https://medium.com/@nikunjmishra8170/deploying-django-api-vue-js-app-with-nginx-using-docker-c8c3d3c7cd08

2023-02-10 04:46 UTC, Ridealist commented
주요 변화
1. docx 파일 만드는 방식 전면 수정
- 별도 템플릿 파일 필요 없음
- 꼬리말 부분에 가사 넣는 방식
- 폰트 크기 적정화 알고리즘 추가

2. 파일 이름 및 형식을 BE에서 지정한 대로 FE에서 다운로드하도록 변경
- FE, Content-Dispotion key값에서 파일 이름 및 형식 받아와 그대로 다운로드 링크 제공

2023-02-11 04:03 UTC, hoetaek requested changes
형 requirements.txt만드는거랑 .env 파일에서 변수 받아오는 부분 확인해줘~
그리고 포트 관련해서 너무 헷갈리는데 내가 이해하는 게 맞아?

1. 8000 Django 백엔드
2. 5173 vue 프론트엔드
3. 80 -> 모르겠음

왜 내 로컬에서 8000 포트랑 5173 포트 둘 다 vite 앱이 열리는지 모르겠고, 80포트로 들어가니까 404에러가 뜨는데 이것도 이해가 잘 안가ㅠ

2023-02-11 23:29 UTC, Ridealist commented on backend/Dockerfile
> +COPY requirements.txt /tmp/requirements.txt
이거 진짜 좋네. Dockerfile 자체에 poetry로 dependency를 설치해버리면 되겠구나.
바로 적용해볼게 땡큐!

2023-02-11 23:33 UTC, Ridealist commented on backend/picture_muvie/settings.py
> +DEBUG = os.getenv("DEBUG", "0").lower() in ["true", "t", "1"]
dev 단계랑 production 단계에서 .env로 settings 조정하려고 추가해놨어.
근데 잡다한 느낌이 없지 않아 있네. 사실 True False로만 처리해도 되는건데. 좀 더 깔끔하게 수정해볼게~

2023-02-11 23:44 UTC, Ridealist commented on backend/pyproject.toml
> +python-dotenv = "^0.21.1"
맞어 나도 찾아보니 둘 다 같은 거라고 하더라고?
나는 항상 장고 쓸 때 저 라이브러리 사용해서 .env 파일 관리했어서 큰 생각 없이 사용했는데 너가 link 달아준 것들 읽어보니
django-environ이 좀 더 django 맞춤형으로 제작된 거라 더 편하겠더라고.
이 library는 삭제하고 아예 django-environ으로 전부 관리하자!

2023-02-12 01:07 UTC, Ridealist commented on backend/picture_muvie/settings.py
> +CORS_ORIGIN_WHITELIST = ["http://127.0.0.1:5173", "http://localhost:5173", "http://localhost:8000", "http://localhost:80"]
이건 어제 얘기했던 부분이네
1. 맞어 "http://localhost:8000" 일단 우리 장고 주소는 cors에 추가할 필요 없겟다
https://stackoverflow.com/questions/47228488/django-allowed-hosts-vs-corsdjango-cors-headers
이거 참고해보면

결국
ALLOWED_HOSTS 는 장고 서버를 돌릴 수 있는 '도메인'을 설정해 주는 것이고
CORS_ORIGIN_WHITELIST 는 장고 api에게 요청을 보내는 것을 허용하는 주소니까 포트까지 전체를 명시해주는 것 같아

우리는 백엔드, 프론트엔드가 다 같은 ec2 인스턴스에 있으니까 도메인은 같겠지
ALLOWED_HOSTS = ['localhost', '127.0.0.1', (ec2 인스턴스 도메인 ip 주소)]
CORS_ORIGIN_WHITELIST = [ (ec2 인스턴스 도메인 ip 주소):(nginx에서 열린 포트 번호)] 이렇게 되겠더라고

2023-02-12 01:25 UTC, hoetaek commented on backend/picture_muvie/settings.py
> +DEBUG = os.getenv("DEBUG", "0").lower() in ["true", "t", "1"]
오키! 가독성 측면에서 물어봤어~ 바로 의도를 알기 힘들어서

2023-02-12 01:26 UTC, hoetaek commented on backend/picture_muvie/settings.py
> +CORS_ORIGIN_WHITELIST = ["http://127.0.0.1:5173", "http://localhost:5173", "http://localhost:8000", "http://localhost:80"]
ㅇㅎ 전혀 몰랐어! 고마워형~

2023-02-12 01:26 UTC, hoetaek commented on backend/pyproject.toml
> +python-dotenv = "^0.21.1"
응 내가 이미 .env파일에서 받아오는 거 설정해뒀었음!

2023-02-12 05:59 UTC, hoetaek commented
형 PR에 .env파일에 적어야 하는 변수들 목록도 정리해줄 수 있어? 리뷰어에게 참고하라는 메시지처럼 말이야

2023-02-12 06:10 UTC, Ridealist commented
> 형 PR에 .env파일에 적어야 하는 변수들 목록도 정리해줄 수 있어? 리뷰어에게 참고하라는 메시지처럼 말이야

PR은 merge되면 닫히니까 파일로 관리하는게 더 나을 것 같아서 파일을 하나 만들었어
개발하면서 추가되는 것들 있으면 .env.sample 에다가 어떤 key들 관리할지 누적에서 적으면 될듯

2023-02-12 07:24 UTC, Ridealist commented
회택아 이거 수정 했거든 확인 좀! @hoetaek

2023-02-12 07:39 UTC, hoetaek commented
> 회택아 이거 수정 했거든 확인 좀! @hoetaek 

응 밖이라서 얼른 들어가 확인할게

2023-02-12 07:59 UTC, hoetaek approved these changes
수고하셨습니다!

2023-02-12 07:59 UTC, hoetaek commented on .dockerignore
> +.gitignore
```suggestion
node_modules
npm-debug.log
Dockerfile*
docker-compose*
.dockerignore
.git
.gitignore
README.md
LICENSE
.vscode
env
```

2023-02-12 07:59 UTC, merged