Recreate making docx File method
teacher-coder/picture-muvie pull request #18
Opened 2023-02-10 04:52 UTC by Ridealist

주요 변화
1. docx 파일 만드는 방식 전면 수정
- 별도 템플릿 파일 필요 없음
- 꼬리말 부분에 가사 넣는 방식
- 폰트 크기 적정화 알고리즘 추가

2. 파일 이름 및 형식을 BE에서 지정한 대로 FE에서 다운로드하도록 변경-
- BE, api.py에서 파일 이름 및 형식 명시해 지정
- FE, Content-Dispotion key값에서 파일 이름 및 형식 받아와 그대로 다운로드 링크 제공

2023-02-11 02:07 UTC, hoetaek commented
@Ridealist 형 수고했어! 그런데 readme 파일은 이번 PR 제목과는 어울리지 않는 것 같음!
다음번 부터는 이렇게 논리적으로 2개로 분류될 수 있는 PR은 분리해서 2개의 PR로 올려줄 수 있을까?

2023-02-11 02:15 UTC, Ridealist commented
> @Ridealist 형 수고했어! 그런데 readme 파일은 이번 PR 제목과는 어울리지 않는 것 같음! 다음번 부터는 이렇게 논리적으로 2개로 분류될 수 있는 PR은 분리해서 2개의 PR로 올려줄 수 있을까?

맞어 하나의 PR에 여러 이슈가 들어가버린 실수ㅠ
한 PR엔 하나의 이슈만 처리하는 것으로!ㅎㅎ 확인~
@hoetaek

2023-02-11 02:25 UTC, hoetaek commented
> > @Ridealist 형 수고했어! 그런데 readme 파일은 이번 PR 제목과는 어울리지 않는 것 같음! 다음번 부터는 이렇게 논리적으로 2개로 분류될 수 있는 PR은 분리해서 2개의 PR로 올려줄 수 있을까?
> 
> 맞어 하나의 PR에 여러 이슈가 들어가버린 실수ㅠ 한 PR엔 하나의 이슈만 처리하는 것으로!ㅎㅎ 확인~ @hoetaek

감사합니다!

2023-02-11 05:15 UTC, hoetaek requested changes

2023-02-11 05:15 UTC, hoetaek commented on backend/picture_muvie/api.py
> +            "Content-Disposition": f'attachment; filename="{file_name}.{file_format}"',
이거 파일 이름 소용은 있어?? 어차피 파일 이름이 동적으로 변하더라도 프론트에 입력하는걸로 정해질거라.. 백엔드에서 나오는 정보로 이름 정해지지는 않을걸?

2023-02-11 05:15 UTC, hoetaek commented on backend/picture_muvie/docs.py
> +def make_doc_title(doc : Document, title : str):
이 부분 #24 이슈 관련해서 word art 적용하면 어떨까 싶은데 어떻게 생각해?

2023-02-11 05:15 UTC, hoetaek commented on backend/picture_muvie/docs.py
> +    make_doc_title(doc, title)
두개 함수 보면 이름은 비슷한데 signature(인터페이스)가 다르지? 통일하면 어떨까??
```suggestion
    doc = Document()
    make_a4_landscape_section(doc)
    make_doc_title(doc, title)
```

2023-02-11 05:15 UTC, hoetaek commented on backend/picture_muvie/docs.py
> +    section = sections[0]
사이즈 적용이 첫번째 섹션에만 되는거지??

2023-02-11 05:15 UTC, hoetaek commented on backend/picture_muvie/docs.py
> +def reform_font_size(paragraph : Paragraph, lyric : str):
함수 이름은 reform인데 사실 상 run을 추가하고 있네!

2023-02-11 05:15 UTC, hoetaek commented on frontend/src/views/HomeView.vue
> +  const filename = response.headers['content-disposition'].split('filename=')[1].replace(/"/g, "")
굳이 header에 파일 이름 포함시키지 말고 차라리 노래 이름을 프론트에서 직접 받아와서 이름으로 설정하면 어떨까?

2023-02-11 05:15 UTC, hoetaek commented on frontend/src/views/HomeView.vue
> +  const filename = response.headers['content-disposition'].split('filename=')[1].replace(/"/g, "")
나중에 백엔드로 파일 이름 또 보내면 불필요한 정보들 보내게 되어서 더 헷갈릴까봐 제안함!

2023-02-12 01:59 UTC, hoetaek requested changes

2023-02-12 01:59 UTC, hoetaek commented on README.md
> +    <a href="https://github.com/github_username/repo_name/issues">Request Feature</a>
이 url들 모두 업데이트 해야합니다!

2023-02-12 01:59 UTC, hoetaek commented on README.md
> +<h3 align="center">Teacher Muvie(Music Video)</h3>
```suggestion
<h3 align="center">Picture Muvie(Music Video)</h3>
```
선생님에 대한 뮤비는 아니니까?

2023-02-12 01:59 UTC, hoetaek commented on README.md
> +    <a href="https://github.com/github_username/repo_name"><strong>Explore the docs »</strong></a>
여기에 원래 프로젝트 설명 써줘야해. 난 아래처럼 했었어~
<img width="859" alt="image" src="https://user-images.githubusercontent.com/14107090/218288847-64d104fc-fc60-4a92-8995-482d3e877cfc.png">

2023-02-12 01:59 UTC, hoetaek commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
여기도! 아래는 내가 만든 예시~
<img width="868" alt="image" src="https://user-images.githubusercontent.com/14107090/218288887-bd16ad5b-b669-4c2e-b1a0-333317cf0552.png">

2023-02-12 05:56 UTC, Ridealist commented on README.md
> +  brew install docker
응 cask 쓰지 않고 brew만으로도 잘 설치 됐었어

2023-02-12 06:18 UTC, Ridealist commented
이게 PR이 섞여서 확실히 알아보기가 힘들다..
일단 내 생각에 README 작성은 후순위인 것 같아서 이거 PR은 README에 대한 걸로 바꿔놓고 나중에 처리하고
docx 부분만 새로 PR 만드는게 좋을 것 같은데 어때?

2023-02-12 06:30 UTC, Ridealist commented on backend/picture_muvie/api.py
> +            "Content-Disposition": f'attachment; filename="{file_name}.{file_format}"',
이 부분은 프론트엔드도 수정해놨거든 그래서 바꾼건데
밑에 회택이 너가 쓴 내용처럼 파일 제목은 사용자가 입력한 노래 제목으로 설정하는게 더 좋아보여 내가 볼 때도~

그래도 파일 형식까지 백엔드에서 정해주는게 더 나을 것 같아 내 생각엔. 백엔드에서 생성된 파일을 프론트엔드에서 전달하는 구조니까
백엔드에서 다 결정된 대로 프론트엔드는 처리만 하는게 더 좋아보여서. 

나중에 백엔드에서 보내주는 파일 형식이 달라졌을 때 프론트엔드, 백엔드 둘다 바꾸는 구조도 비효율적이고.

{title}.{file_format} 형식으로 보내주는 파일이름을 백엔드에서 보내주면 프론트은 그대로 다운로드 링크만 생성하도록.

2023-02-12 07:06 UTC, Ridealist commented on backend/picture_muvie/docs.py
> +def make_doc_title(doc : Document, title : str):
word art 적용한번 해볼게~

2023-02-12 07:08 UTC, Ridealist commented on backend/picture_muvie/docs.py
> +    make_doc_title(doc, title)
오키 통일성을 위해 그게 낫겠다 수정할게 이것도

2023-02-12 07:09 UTC, Ridealist commented on backend/picture_muvie/docs.py
> +    section = sections[0]
계속 적용되면서 section을 만드는 구조!

2023-02-12 07:12 UTC, hoetaek commented
> 이게 PR이 섞여서 확실히 알아보기가 힘들다..
> 
> 일단 내 생각에 README 작성은 후순위인 것 같아서 이거 PR은 README에 대한 걸로 바꿔놓고 나중에 처리하고
> 
> docx 부분만 새로 PR 만드는게 좋을 것 같은데 어때?
> 
> @hoetaek 

브렌치를 따로 파고 새로 pr 올리자!

2023-02-12 07:12 UTC, Ridealist commented on backend/picture_muvie/docs.py
> +def reform_font_size(paragraph : Paragraph, lyric : str):
reform할 글자를 run 객체로 만들기 위해서 run을 추가하는 거야.
run 객체를 통해서 글자 크기나 글자 폰드를 수정할 수 있어서.

reform_font_size가 의미가 좀 안드러 나긴 하네 그래도. make_formatted_lyric 표현이 더 적절해 보인다

2023-02-12 07:14 UTC, Ridealist commented
응 이 PR은 놔두고 docx 파일 만드는 부분만 따로 PR 올릴게

2023-02-12 07:14 UTC, hoetaek commented on backend/picture_muvie/api.py
> +            "Content-Disposition": f'attachment; filename="{file_name}.{file_format}"',
음.. 한글 파일이랑 워드 파일이랑 선택해서 받을 수 있도록 할까 하거든. 그러면 확장자명도 프론트에서 정하는게 나을듯!

2023-02-13 00:00 UTC, Ridealist commented on backend/picture_muvie/api.py
> +            "Content-Disposition": f'attachment; filename="{file_name}.{file_format}"',
맞어 나도 사용자에게 선택지를 주면 좋겠다 생각은 했는데, 한글이랑 워드랑 혹시 파일 연동이 잘 안되면 별도의 탬플릿을 만들어야 되나 생각을 했지.

2023-02-13 00:01 UTC, Ridealist commented on backend/picture_muvie/api.py
> +            "Content-Disposition": f'attachment; filename="{file_name}.{file_format}"',
그럼 요청할 때 어떤 파일 형식을 원하는지도 같이 넘겨줄래 프론트에서? 그거 보고 탬플릿 결정해서 백엔드에서 쏴주는걸로.

2023-02-13 00:02 UTC, Ridealist commented on backend/picture_muvie/api.py
> +            "Content-Disposition": f'attachment; filename="{file_name}.{file_format}"',
![image](https://user-images.githubusercontent.com/89024993/218345123-5031d46e-1ab7-4878-9212-72c30cc62d38.png)

(참고로 지금 문서를 한글에서 열면 이렇게 너무 가사가 밑에 치우쳐서 나와. 이것도 수정이 필요함.)

2023-02-13 22:03 UTC, hoetaek commented
@Ridealist 형 이거 내가 수정할게!

2023-02-13 23:06 UTC, Ridealist commented
> @Ridealist 형 이거 내가 수정할게!

오 그래주면 고맙지~ 땡큐!

2023-02-14 13:37 UTC, closed without merging