Feat: makedocx app 추가
teacher-coder/picture-muvie pull request #3
Opened 2023-02-06 02:49 UTC by Ridealist

- startapp으로 makedocx 디렉토리 생성
- form + html 탬플릿 활용해 간단한 화면 구성
- view에 변환 로직 코드 작성

2023-02-06 08:49 UTC, hoetaek commented
@Ridealist 형 pull request dev로 보내야지!

2023-02-06 08:54 UTC, Ridealist commented
앗 이런 실수를... 오키 dev로 수정했다!
@hoetaek

2023-02-06 11:45 UTC, hoetaek commented on makedocx/api.py
> +    return render(request, "html/lyrics.html", {"form": form})
형 이거 어차피 vue로 할거라서 reder 못할거야~

2023-02-06 11:45 UTC, hoetaek commented on makedocx/api.py
> +def make_header(title: str, artist: str):
우리 docx 만드는 코드들은 다르 파일에다 모아두자! utils.py도 좋고 service.py도 좋고~ 형이 원하는 이름으로

2023-02-06 11:45 UTC, hoetaek commented on makedocx/api.py
> +def lyrics_post(request, song: Song = Form(...)):
Form 관련해서 나도 공식문서에서 스치듯이 읽기만 했는데 vue랑 사용할 때도 가능한거야?
보통 form을 사용하는 이유는 validate 때문인걸로 알고 있는데 혹시 pydantic schema로 부족한건지도 궁금해!

2023-02-06 11:45 UTC, hoetaek commented on makedocx/templates/html/lyrics.html
> +<html>
어차피 html 여기 있는건 사용 안할듯?? 형이 만들어둔 건 참고할게. text input 두개랑 text area input 1개면 되는거지?

2023-02-06 11:45 UTC, hoetaek commented on makedocx/api.py
> +from docx import Document as Document_compose
혹시 이거 alias 만든 이유는 뭐야??

2023-02-06 11:45 UTC, hoetaek commented on makedocx/api.py
> +    doc.save("output/lyrics_header.docx")
save 안하고도 문서끼리 합칠 수 있는 방법 없나? 새로운 요청 들어올 때마다 파일을 계속 덮어쓰는 방법으로 하는거지?

2023-02-06 11:45 UTC, hoetaek commented on makedocx/api.py
> +    make_body(title, artist, lyric)
이렇게 하면 모든 페이지에 노래 제목이랑 가수가 들어가는건가?

2023-02-06 11:51 UTC, hoetaek commented
실행해봤는데 이런 에러 뜨네! @Ridealist 
`FileNotFoundError: [Errno 2] No such file or directory: 'output/lyrics_header.docx'`

2023-02-06 11:53 UTC, hoetaek commented on makedocx/api.py
> +    make_body(title, artist, lyric)
다음번에 PR 올릴 때 출력 결과물도 스크린샷해서 올려줄 수 있어?

2023-02-06 11:54 UTC, hoetaek commented on makedocx/api.py
> +    make_body(title, artist, lyric)
그리고 이거 한번 우리 프린트해서 봐봐도 좋을듯!

2023-02-06 11:55 UTC, hoetaek commented on makedocx/api.py
> +    return render(request, "html/lyrics.html", {"form": form})
나는 이런식으로 테스트를 했어~
![image](https://user-images.githubusercontent.com/14107090/216965094-3cfa9413-7e04-46ec-8245-aca0dc7774ec.png)

2023-02-06 11:58 UTC, hoetaek commented on pyproject.toml
> +docxcompose = "^1.4.0"
docxcompose 사용한하고 subdoc 사용하는건 혹시 해봤어? 둘 중에 어떤 게 더 나을지 하거든. 일단 아래에 레퍼런스 링크 올려둘게
내가 생각하는 docxcompose의 단점은 실제로 파일을 저장해야 한다는거야~

https://github.com/elapouya/python-docx-template/blob/master/tests/subdoc.py

2023-02-07 02:33 UTC, Ridealist commented on makedocx/api.py
> +    return render(request, "html/lyrics.html", {"form": form})
맞어 render 못하긴 할텐데, 내가 테스트 할 때 화면에 보이는것이랑 어떻게 연동되는지 확인하려고 남겨 놨었어.
지워도 무방한 코드긴 하니 없애지 뭐~

2023-02-07 02:41 UTC, Ridealist commented on makedocx/api.py
> +def make_header(title: str, artist: str):
비즈니스 로직을 분리해서 관리하자는 거지? 좋은 생각이다 오키!

2023-02-07 02:46 UTC, Ridealist commented on makedocx/templates/html/lyrics.html
> +<html>
응 맞어 vue랑 연동되면 사용할 필요 없지. 일단은 놔두고 vue 연동되면 지울게

2023-02-07 02:47 UTC, Ridealist commented on makedocx/api.py
> +from docx import Document as Document_compose
특별한 이유는 없어. stackoverflow에서 참고한 코드라 그대로 썼었어.
가독성이 오히려 떨어지면 Document로 써도 괜춘~

2023-02-07 02:52 UTC, Ridealist commented on pyproject.toml
> +docxcompose = "^1.4.0"
맞어 그게 제일 단점이긴 해. 근데 반대로 subdoc을 활용하면 페이지가 내부에 삽입되는 방식이라 페이지 내에 가사 위치를 조정하기가 어려웠어. 가사는 항상 일정한 위치에 찍혀야 되니깐.

2023-02-07 02:53 UTC, Ridealist commented on pyproject.toml
> +docxcompose = "^1.4.0"
이건 좀 더 고민해볼게 나도

2023-02-07 02:54 UTC, Ridealist commented on makedocx/api.py
> +    doc.save("output/lyrics_header.docx")
> 실행해봤는데 이런 에러 뜨네! @Ridealist `FileNotFoundError: [Errno 2] No such file or directory: 'output/lyrics_header.docx'`

이건 output 폴더가 없어서 발생하는 에러다.
push 할 때 output 폴더에 생성된 docx파일들은 다 지우고 올렸는데 거기서 output 폴더 자체도 push가 안됐나보네.

2023-02-07 02:55 UTC, Ridealist commented on makedocx/api.py
> +def lyrics_post(request, song: Song = Form(...)):
이건 나도 찾아봐야겠다. vue 연동가능한지 여부랑 너가 얘기한 부분 확인해볼게~

2023-02-07 03:18 UTC, Ridealist commented on makedocx/api.py
> +    make_body(title, artist, lyric)
출력 파일 카카오톡으로 보내놨어~
일단 잘 나오는 것까지는 확인!

2023-02-07 04:58 UTC, Ridealist commented on makedocx/api.py
> +def lyrics_post(request, song: Song = Form(...)):
일단 form으로 해도 vue랑 연동은 가능해보여. 사실 form이란게 html form 태그를 조작하기 위한 클래스들 이잖아. vue에서 form tag를 이용해서 입력 칸을 만들면 되는거니까. 근데 우린 값 validation이 따로 필요한 건 아니니 굳이 form을 통해 데이터를 주고 받을 필욘 없어보이네.

2023-02-07 04:59 UTC, Ridealist commented on makedocx/api.py
> +def lyrics_post(request, song: Song = Form(...)):
회택이 너 말처럼 pydantic schema로도 기본적인 type checking이 가능하고. pydentic schema에서 validator 데코레이터를 통해 유효성 검사도 가능하더라고.

2023-02-07 08:14 UTC, hoetaek requested changes

2023-02-07 08:14 UTC, hoetaek commented on makedocx/api.py
> +        doc_compose(composer, title, artist, lyric)
```suggestion
        doc2 = make_body(title, artist, lyric)
     composer.append(doc2)
```

2023-02-07 09:39 UTC, hoetaek approved these changes

2023-02-07 09:47 UTC, merged