배포 버젼 검색 오류에 대한 Naver 검색 적용
teacher-coder/picture-muvie pull request #70
Opened 2023-02-19 04:18 UTC by Ridealist

1. naver 웹페이지 검색 API 활용
- https://developers.naver.com/docs/serviceapi/search/blog/blog.md#%EB%B8%94%EB%A1%9C%EA%B7%B8
- 25,000쿼리/day 무료 허용

2. 검색 api -> 가사 url links 확보
3. links 종류 별로 scrap 요소 다르게 적용해 가사 확보
4. 가사가 확보되면 return / 없으면 none 반환

2023-02-20 00:58 UTC, hoetaek commented
@Ridealist 네이버 검색은 실패하는 경우가 거의 없지?
가사가 어느 사이트에서 긁어와졌는지 출처를 표시할 필요는 없나? 네이버나 구글 검색 엔진도 출처를 표기하니까 혹시 몰라서!

2023-02-20 02:48 UTC, hoetaek requested changes

2023-02-20 02:48 UTC, hoetaek commented on backend/picture_muvie/utils/naver_search.py
> +        if response.status_code == 200:
아예 exception 생기도록 해보면 어떨까? 아래 logger.debug의 의미가 더 분명해질듯!
`response.raise_for_status()`
https://docs.python-requests.org/en/latest/user/quickstart/#response-status-codes

2023-02-20 02:50 UTC, hoetaek commented on backend/picture_muvie/utils/naver_search.py
> +            text += "\n"
형 여기서 delimiter 영향이 있는건가?

2023-02-20 06:48 UTC, Ridealist commented
> @Ridealist 네이버 검색은 실패하는 경우가 거의 없지? 가사가 어느 사이트에서 긁어와졌는지 출처를 표시할 필요는 없나? 네이버나 구글 검색 엔진도 출처를 표기하니까 혹시 몰라서!

오키 확인! 출처 표기하도록 수정해서 추가 commit 올릴게~

2023-02-20 06:49 UTC, Ridealist commented
와 꼼꼼히 코멘트 달아줬네~~ 이따 스터디 공부 마무리하고서 하나씩 확인해볼게! 코멘트 땡큐:)
@hoetaek

2023-02-21 04:18 UTC, Ridealist commented on backend/picture_muvie/api.py
> +# from .utils.search_lyrics import get_lyrics
나도 삭제할까 하다가 너가 열심히 짠건데 지우기 그래서 냅뒀지. 영어 가사를 받아오는 기능을 더 쓸 수도 있을 것 같고.
musixmatch  bot detection 우회하는거 코딩해보고 싶기도 해ㅋㅋㅋㅋ

2023-02-21 04:31 UTC, Ridealist commented on backend/picture_muvie/utils/naver_search.py
> +            lyrics = None
그런게 있는지 몰랐네? 오키 보고서 적용해볼게 땡큐!

2023-02-21 04:52 UTC, Ridealist commented on backend/picture_muvie/utils/naver_search.py
> +            return lyrics
가끔보면 가사가 짤린게 올라가 있거나, 가사가 아닌 글이 설명글?이 들어가 있는 경우가 있더라고.
그거에 대한 예외처리 용도야.

2023-02-21 04:53 UTC, Ridealist commented on backend/picture_muvie/utils/naver_search.py
> +    rescode = response.getcode()
특별한 이유는 없고 네이버 api 문서에 이렇게 예시 코드가 나와있더라고? 그래서 일단 그대로 반영해봤어.
https://developers.naver.com/docs/serviceapi/search/blog/blog.md#python

2023-02-21 04:57 UTC, Ridealist commented on backend/picture_muvie/utils/naver_search.py
> +        artist = ""
오 좋은 생각이다. default를 "" blank로 처리하는게 낫겠네

2023-02-21 04:58 UTC, Ridealist commented on backend/picture_muvie/utils/naver_search.py
> +        return
좋은 생각 그게 더 코드 가독성이 좋네~~

2023-02-21 04:59 UTC, hoetaek commented on backend/picture_muvie/api.py
> +# from .utils.search_lyrics import get_lyrics
ㅋㅋㅋㅋ 기록에는 남아있으니까 안 쓰면 상관없지~ 뭐 형말대로 영어 검색 때 사용해도 되고

boto3 사용하면 ec2의 ip 주소 바꿀 수 있는데ㅋㅋㅋ 예전에 그걸로 우회하고는 했었어

2023-02-21 05:01 UTC, Ridealist commented on backend/picture_muvie/utils/naver_search.py
> +        return
나는 java를 써봐서 그런가? 명시적 표현이 좋더라고. return 값이 모든 경우에 대해 정의가 안돼어 있으면 compiler error가 나는데
쓰다보니 그게 더 좋더라고. 코드 구조를 이해하기 편해서. return 값이 있는 함수는 모든 경우에 대해 return 값을 명시해 주는걸 선호!

2023-02-21 13:28 UTC, Ridealist commented on backend/picture_muvie/utils/naver_search.py
> +            lyrics = None
보니까 match case는 조건 분기문을 거친 다음 다시 전체에 대해 적용하는 코드를 처리하기 어렵더라고?
각 결과에 따라 다 처리가 모두 다른경우면 모를까 우리는 함수들로부터 변수값을 받아와서
그 변수값을 전달해야 되는거니까 적용이 어려워 보였어.
그래서 Enum을 사용해봤어 리뷰 부탁~

2023-02-21 14:05 UTC, hoetaek commented on backend/picture_muvie/utils/naver_search.py
> +            lyrics = None
그러게 다시 보니까 in 키워드 사용해서 내가 생각했던거랑 다르더라고ㅋㅋㅋ

2023-02-21 14:13 UTC, Ridealist commented on backend/picture_muvie/utils/naver_search.py
> +            lyrics = None
방금 push 했다! @hoetaek

2023-02-21 14:15 UTC, Ridealist commented on backend/picture_muvie/utils/naver_search.py
> +            text += "\n"
이거 영향 있어. lyrics.co.kr 사이트는 사이사이에 br p 태그가 있더라고
lyrics 필드안에 또 html tag가 있는 구조지.
이건 text로 바로 가져오는 것보다 elemant 하나씩 접근해서 바꾸는가면서 text 빌드하는게 더 깔끔해서 이렇게 했어.

2023-02-21 14:26 UTC, Ridealist commented on backend/picture_muvie/utils/naver_search.py
> +        if response.status_code == 200:
이것도 적용했어. 확실히 코드의 의도가 더 분명해지네 exception 처리까지 명시하니깐

2023-02-21 14:28 UTC, hoetaek reviewed
와우 수고했다!
여기 보면 연 구분되었던 애들은 띄어쓰기 2번으로 처리되는 거 같더라고
이거 수정하면 좋을듯 !
![image](https://user-images.githubusercontent.com/14107090/220372356-98d4243c-736b-4646-9e89-8a49be508e55.png)

2023-02-21 14:29 UTC, hoetaek commented
![image](https://user-images.githubusercontent.com/14107090/220372471-9da6d7dc-17ae-4ae7-b3e0-2d2f23435c3b.png)
여기 보면 뉴진스 ditto 검색 못했다고 하는데 이건 그러면 어떤 음악 사이트에도 검색 안되는거지?

2023-02-21 14:30 UTC, Ridealist commented
> ![image](https://user-images.githubusercontent.com/14107090/220372471-9da6d7dc-17ae-4ae7-b3e0-2d2f23435c3b.png) 여기 보면 뉴진스 ditto 검색 못했다고 하는데 이건 그러면 어떤 음악 사이트에도 검색 안되는거지?

뉴진스가 newjeans 영어 정식 명칭이라 그럴거야 제목만 쳐도 나올걸 아니면?

2023-02-21 14:46 UTC, hoetaek commented
응응 그렇게 하면 되는거지 확인했는데 네이버에는 한글로 쳐도 나오는데 이렇게는 검색이 안되는게 이상해서ㅋㅋㅋ 이런 예외 케이스들 계속
나올테니까 모아서 처리하지 뭐

On Tue, Feb 21, 2023 at 11:30 PM Junbo Koh ***@***.***> wrote:

> [image: image]
> <https://user-images.githubusercontent.com/14107090/220372471-9da6d7dc-17ae-4ae7-b3e0-2d2f23435c3b.png>
> 여기 보면 뉴진스 ditto 검색 못했다고 하는데 이건 그러면 어떤 음악 사이트에도 검색 안되는거지?
>
> 뉴진스가 newjeans 영어 정식 명칭이라 그럴거야 제목만 쳐도 나올걸 아니면?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/teacher-coder/picture-muvie/pull/70#issuecomment-1438589030>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADLUDUWS6VHSAYJLRPQOCRDWYTGQZANCNFSM6AAAAAAVAXMXT4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-21 14:56 UTC, hoetaek approved these changes
저거 하나만 고치면 되니까 approve해둘게. 수고했습니다!!

2023-02-22 02:45 UTC, Ridealist commented
> 저거 하나만 고치면 되니까 approve해둘게. 수고했습니다!!

이건 지금 네이버 검색 API 상 금방 고치기 힘들겠더라.
네이버 검색엔진의 일부 기능만 사용하는지 블로그 글들만 받아와지더라고. 음원 사이트 링크들을 받아오질 못하네.
블로그 글들은 가사 부분이 다 천차만별이라 scrapping을 일괄로 돌리긴 힘들고.

2023-02-22 02:46 UTC, Ridealist commented
당장 구현은 힘드니 backlog로 남겨놓고 가사 검색 방식을 업데이트 하고,
임시 방편으로 구글 검색 창을 하나 달아주는 식으로 처리해야 될듯.
가사 검색 안되면 구글 검색 창에서 사용자 스스로 찾도록. @hoetaek

2023-02-22 03:06 UTC, merged